
name: Build Angular App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
  
      - name: Install dependencies
        run: npm install
  
      - name: Build project
        run: npm run build

      - name: Step 4 - List out from current directory
        run: ls -a

      - name: Step 5 - Target Folder location
        run: |
          cd dist
          ls -a 



  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - run: mkdir staging && cp -r dist staging
    - uses: actions/upload-artifact@v3
      with:
        name: Artifact
        path: staging
      
